pkgname = "models"
output = "pkg/sqlboiler/models"
wipe = true
no-tests = true
add-enum-types = true

[psql]
dbname = "postgres"
host = "localhost"
port = 5432
user = "postgres"
pass = "postgres"
schema = "public"
sslmode = "disable"

[[types]]
[types.match]
db_type = "uuid"

[types.replace]
type = "uuid.UUID"

[types.imports]
third_party = [ "\"github.com/google/uuid\"" ]
